import type { Metadata } from "next";
import {Inter, Lato} from "next/font/google";
import "./globals.css";
import {NextFont} from "next/dist/compiled/@next/font";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
